source "https://rubygems.org"

gem "jekyll", "~> 4.2.0"

gem "jekyll-theme-chaos", path: ".."

group :jekyll_plugins do
  gem "jekyll-airtable-import", "~> 0.1.0"
end

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]
